spring.application.name=backend

# DATABASE CONNECTION
spring.datasource.url=jdbc:mysql://localhost:3306/billpoint_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# HIBERNATE / JPA CONFIGURATION
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# JWT CONFIG
# ===============================
jwt.secret=4f7a9d02c81a5e1d99b7c3d2e5a1098b0f8c3725b8a011a0b3c2e17586a9d59e
jwt.expirationMs=86400000

# ===============================
# SERVER
# ===============================
server.port=8080

# LOG FILE
logging.file.name=application-error.log